Chargement du dataset CSV dans un DataFrame df avec Pandas. Affichage des premières lignes pour vérifier la structure des données.

In [1]:
import pandas as pd
df = pd.read_csv('phishing_emails.csv')
df.head()

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1

Affiche le nombre total d’e-mails dans le dataset.

In [2]:
len(df)

39154

Affiche des informations générales sur le DataFrame (colonnes, types, valeurs nulles…).

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39154 entries, 0 to 39153
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sender    39154 non-null  object
 1   receiver  38692 non-null  object
 2   date      39154 non-null  object
 3   subject   39126 non-null  object
 4   body      39154 non-null  object
 5   label     39154 non-null  int64
 6   urls      39154 non-null  int64
dtypes: int64(2), object(5)
memory usage: 2.1+ MB

Compte le nombre d’e-mails légitimes (label = 0).

In [4]:
len(df[df.label == 0])

17312

Compte le nombre d’e-mails spam/phishing (label = 1).

In [5]:
len(df[df.label == 1])

21842

In [6]:
df = df[['sender', 'subject', 'body', 'label']]

In [7]:
df

,sender,subject,body,label
0,Young Esposito <Young@iworld.de>,Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1
1,Mok <ipline's1983@icable.ph>,Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1
3,Michael Parker <ivqrnai@pobox.com>,Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0
4,Gretchen Suggs <externalsep1@loanofficertool.com>,SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1
...,...,...,...,...
39149,CNN Alerts <charlene-detecton@btcmarketing.com>,CNN Alerts: My Custom Alert,\n\nCNN Alerts: My Custom Alert\n\n\n\n\n\n\n ...,1
39150,CNN Alerts <idgetily1971@careplusnj.org>,CNN Alerts: My Custom Alert,\n\nCNN Alerts: My Custom Alert\n\n\n\n\n\n\n ...,1
39151,Abhijit Vyas <xpojhbz@gmail.com>,Slideshow viewer,Hello there ! \nGreat work on the slide show v...,0
39152,Joseph Brennan <vupzesm@columbia.edu>,Note on 2-digit years,"\nMail from sender , coming from intuit.com\ns...",0
39153,Christian Heimes <wluhe@cheimes.de>,[Python-Dev] PEP 370 heads up,Dear fellow Pythonistas!\n\nGuido has accepted...,0

In [8]:
import re

def clean_text_keep_urls(text):
    if pd.isnull(text):
        return ""
    text = text.lower()
    text = re.sub(r"[^a-z0-9:/.\s@]", " ", text)  # garde urls, emails
    text = re.sub(r"\s+", " ", text).strip()
    return text

df['sender'] = df['sender'].apply(clean_text_keep_urls)
df['subject'] = df['subject'].apply(clean_text_keep_urls)
df['body'] = df['body'].apply(clean_text_keep_urls)

In [9]:
df.drop_duplicates(inplace=True)
df.dropna(subset=['sender', 'subject', 'body', 'label'], inplace=True)

In [10]:
df

,sender,subject,body,label
0,young esposito young@iworld.de,never agree to be a loser,buck up your troubles caused by small dimensio...,1
1,mok ipline s1983@icable.ph,befriend jenna jameson,upgrade your sex and pleasures with these tech...,1
2,daily top 10 karmandeep opengevl@universalnet....,cnn.com daily top 10,the daily top 10 from cnn.com top videos and s...,1
3,michael parker ivqrnai@pobox.com,re: svn commit: r619753 in /spamassassin/trunk...,would anyone object to removing .so from this ...,0
4,gretchen suggs externalsep1@loanofficertool.com,specialpricespharmmoreinfo,welcomefastshippingcustomersupport http://7iwf...,1
...,...,...,...,...
39149,cnn alerts charlene detecton@btcmarketing.com,cnn alerts: my custom alert,cnn alerts: my custom alert alert name: my cus...,1
39150,cnn alerts idgetily1971@careplusnj.org,cnn alerts: my custom alert,cnn alerts: my custom alert alert name: my cus...,1
39151,abhijit vyas xpojhbz@gmail.com,slideshow viewer,hello there great work on the slide show viewe...,0
39152,joseph brennan vupzesm@columbia.edu,note on 2 digit years,mail from sender coming from intuit.com server...,0
39153,christian heimes wluhe@cheimes.de,python dev pep 370 heads up,dear fellow pythonistas guido has accepted my ...,0

In [11]:
len(df)

39007

In [12]:
len(df[df.label == 0])

17293

In [13]:
len(df[df.label == 1])

21714

In [14]:
spam_df = df[df.label == 1].sample(n=10000, random_state=42)
ham_df = df[df.label == 0].sample(n=10000, random_state=42)
df_balanced = pd.concat([spam_df, ham_df]).sample(frac=1, random_state=42).reset_index(drop=True)

In [16]:
df_balanced.to_csv("balanced_emails_dataset.csv", index=False)